export const commons = {
    "Ilustracija": "插图",
    "FerTutor": "FerTutor",
    "Facebook": "Facebook",
    "Twitter": "Twitter",
    "O nama": "关于我们",
    "Postani instruktor": "成为导师",
    "Cjenik": "价格表",
    "Sigurnost": "安全",
    "Podrška": "支持",
    "Centar za pomoć": "帮助中心",
    "Česta 问题 (FAQ)": "常见问题 (FAQ)",
    "Kontakt": "联系方式",
    "Uvjeti korištenja": "使用条款",
    "Zagreb, Hrvatska": "克罗地亚，萨格勒布",
    "Toggle password visibility": "切换密码可见性",
    "Logo": "标志",
    "Početna": "首页",
    "Instruktori": "导师",
    "Kvizovi": "测验",
    "Registracija": "注册",
    "Prijava": "登录",
    "Profilna Slika": "头像",
    "Preview": "预览",
    "Ukupno korisnika": "总用户数",
    "Studenata": "学生数",
    "Instruktora": "导师数",
    "Verificiranih": "已验证数",
    "Ukupno rezervacija": "总预约数",
    "Završenih lekcija": "已完成课程数",
    "Prosječna ocjena": "平均评分",
    "Recenzija": "评价",
    "Kvizova": "测验数",
    "Pokušaja kvizova": "测验尝试次数",
    "Suspendiranih": "被封禁数",
    "Administratora": "管理员数",
    "Predmet": "科目",
    "Broj rezervacija": "预约数量",
    "Sve uloge": "所有角色",
    "Studenti": "学生",
    "Administratori": "管理员",
    "Svi statusi": "所有状态",
    "Aktivni": "活跃",
    "Suspendirani": "已封禁",
    "Verificirani instruktori": "已验证导师",
    "Neverificirani instruktori": "未验证导师",
    "Admin": "管理员",
    "Suspendiran": "已封禁",
    "+ Dodaj predmet": "+ 添加科目",
    "Prijava potrebna": "需要登录",
    "Prethodni mjesec": "上个月",
    "Sljedeći mjesec": "下个月",
    "Dodajte svoj prvi termin koristeći formu iznad": "使用上方表单添加您的第一个预约",
    "Potražite instruktore i rezervirajte termin": "搜索导师并预约时间",
    "Ispunite detalje za novi termin": "填写新预约的详细信息",
    "1 na 1": "一对一",
    "集体课": "小组课",
    "Nemate dodanih predmeta": "您尚未添加任何科目",
    "Odaberite predmet": "选择科目",
    "Online": "在线",
    "Uživo": "线下",
    "Unesite adresu": "输入地址",
    "Pristup odbijen": "访问被拒绝",
    "Kreiraj novi kviz": "创建新测验",
    "Osnovne informacije": "基本信息",
    "Naslov kviza *": "测验标题 *",
    " Matematika - Kvadratne jednadžbe": " 数学 - 二次方程",
    " Zagreb": " 萨格勒布",
    " Magistar matematike": " 数学硕士",
    "Opis (opcionalno)": "描述 (可选)",
    "Predmet *": "科目 *",
    "Odaberi predmet": "选择科目",
    "Vrijeme 每题 (sekunde)": "每题时间 (秒)",
    "问题": "问题",
    "Bodovi za ovo pitanje:": "本题分数:",
    "Osnovni osobni podaci": "基本个人信息",
    "Ime*": "名字 *",
    "Prezime*": "姓氏 *",
    "Datum rođenja": "出生日期",
    "Spol*": "性别 *",
    "Muški": "男",
    "Ženski": "女",
    "Ostalo / Ne želim reći": "其他 / 不愿透露",
    "Tip Korisnika*": "用户类型 *",
    "Student": "学生",
    "Profesor": "教师",
    "Grad*": "城市 *",
    "Škola / Fakultet*": "学校/学院 *",
    "Edukacija / Stručna sprema*": "教育/学历 *",
    "Zaboravili ste lozinku?": "忘记密码？",
    "Zahtjev zaprimljen": "请求已收到",
    "Email Adresa": "邮箱地址",
    "Još uvijek nemate pristup?": "仍然无法访问？",
    "Vratite se na prijavu": "返回登录",
    "spinning chaos": "旋转混乱",
    "DOBRO DOŠLI": "欢迎",
    "PROCES": "流程",
    "Kako FerTutor funkcionira?": "FerTutor 如何运作？",
    "Pronađi instruktora": "寻找导师",
    "Rezerviraj termin": "预约时间",
    "Počni učiti": "开始学习",
    "Preporučeni instruktori": "推荐导师",
    "Provjeren instruktor": "已验证导师",
    "po satu": "每小时",
    "Što kažu naši korisnici": "用户评价",
    "Maturant": "高中毕业生",
    "Studentica FER-a": "FER 学生",
    "TR": "TR",
    "Roditelj": "家长",
    "Ocjena": "评分",
    "Komentar (opcionalno)": "评论 (可选)",
    "Potvrda rezervacije": "确认预约",
    "-- Odaberi predmet --": "-- 选择科目 --",
    "Bilješka za instruktora": "给导师的备注",
    "Pay": "支付",
    "Broj kartice": "卡号",
    "Ime vlasnika kartice": "持卡人姓名",
    "IME PREZIME": "姓名",
    "Datum isteka": "有效期",
    "Verificirani instruktor": "已验证导师",
    "slobodnih termina": "空闲时间",
    "YouTube video": "YouTube 视频",
    "Budite prvi koji će ostaviti recenziju!": "成为第一个留下评论的人！",
    "Odaberite dan u kalendaru ili pregledajte sve termine ispod": "选择日历中的日期或查看下方所有时间",
    "Pokušajte odabrati drugi dan ili se vratite kasnije": "尝试选择其他日期或稍后再来",
    "Način predavanja": "授课方式",
    "Sve": "全部",
    "线下和线上": "线下和线上",
    "Max cijena (€)": "最高价格 (€)",
    "Predmeti": "科目",
    "Sortiranje po cijeni": "按价格排序",
    "Bez sortiranja": "不排序",
    "Uzlazno": "升序",
    "Silazno": "降序",
    "Nema slobodnih termina": "没有空闲时间",
    "Osobni Interesi": "个人兴趣",
    "Lozinka": "密码",
    "Zapamti prijavu": "记住登录",
    "Još nemate račun?": "还没有账户？",
    "Greška": "错误",
    "Kamera isključena": "摄像头关闭",
    "Napusti poziv": "离开通话",
    "Upravljajte svojim osnovnim informacijama": "管理您的基本信息",
    "Ime": "名字",
    "Vaše ime": "您的名字",
    "Prezime": "姓氏",
    "Vaše prezime": "您的姓氏",
    "Odaberi": "选择",
    "Muško": "男",
    "Žensko": "女",
    "Naziv obrazovne ustanove": "教育机构名称",
    "Odaberite predmete koji vas zanimaju": "选择您感兴趣的科目",
    "Informacije vidljive studentima koji traže instruktore": "信息对寻找导师的学生可见",
    "Ocjene i komentari od vaših studenata": "来自学生的评分和评论",
    "Još nemate recenzija": "暂无评价",
    "Testiraj svoje znanje uz zabavne kvizove!": "通过有趣的测验测试你的知识！",
    "Svi predmeti": "所有科目",
    "Provjerite email!": "检查您的邮箱！",
    "Potvrdi Lozinku": "确认密码",
    "Minimalni zahtjevi za lozinku:": "密码最低要求:",
    "Najmanje 8 znakova": "至少8个字符",
    "Barem jedno veliko slovo": "至少一个大写字母",
    "Barem jedan broj": "至少一个数字",
    "Barem jedan specijalni znak": "至少一个特殊字符",
    "Već imate račun?": "已有账户？",
    "Postavite novu lozinku": "设置新密码",
    "Uspjeh!": "成功！",
    "Nova lozinka": "新密码",
    "Potvrdite lozinku": "确认密码",
    "Imate poteškoća sa lozinkom?": "密码有问题？",
    "返回 na kvizove": "返回测验列表",
    "每题": "每题",
    "Bodovi": "分数",
    "Kviz završen!": "测验完成！",
    "Potvrda Email Adrese": "邮箱确认" ,
    "Registrirajte se kako biste pristupili rezervacijama, instruktorima i personaliziranom učenju.": "注册以访问预约、导师和个性化学习。",
    "Prijavite se i otključajte sljedeći korak u svom učenju personalizirano, fleksibilno i vođen vašim tempom.": "登录并解锁您个性化学习、灵活且以您的节奏进行的下一步。",
    "Lozinke se ne podudaraju.": "密码不匹配。",
    "Morate prihvatiti uvjete korištenja.": "您必须接受使用条款。",
    "Korisnik s ovim emailom već postoji.": "该邮箱已存在。",
    "Link za potvrdu poslan je na vaš email. Molimo provjerite sandučić.": "验证链接已发送到您的邮箱。请检查您的邮箱。",
    "Link za potvrdu poslan je na vaš email. Molimo provjerite sandučić.": "验证链接已发送到您的邮箱。请检查您的邮箱。",
    "Lozinka mora imati 8-32 znakova, veliko i malo slovo, broj i specijalni znak.": "密码必须包含8-32个字符、大写和小写字母、数字和特殊字符。",
    "molas prihvatiti TaC": "您必须接受使用条款。",
    "slanje emaila neuspjesno": "发送邮件失败。",
    "Link za potvrdu poslan je na vaš email. Molimo provjerite sandučić.": "验证链接已发送到您的邮箱。请检查您的邮箱。",
    "Potvrda Registracije | Fertutor.xyz": "注册确认 | Fertutor.xyz",    
    "Slanje...": "发送...",
    "Registrirajte se": "注册",
    "Prijavite se za pregled i upravljanje terminima": "登录以查看和管理预约",
    "Nema rezervacija": "没有预约",
    "Unesite napomenu za instruktora": "输入给导师的备注",
    "Učitavanje mape": "加载地图",
    "Samo profesori mogu kreirati kvizove": "只有教师可以创建测验",
    "Kratki opis kviza": "测验简短描述", 
    "npr": "例如",
    "Upiši pitanje": "输入问题",
    "Sa znakom * označena obavezna polja": "带 * 的必填字段",
    "Kontaktirajte podršku": "联系支持",
    "Pretraži bazu provjerenih instruktora prema predmetu, cijeni ili ocjenama": "按科目、价格或评分搜索验证过的导师",
    "Odaberi vrijeme koje ti odgovara i rezerviraj termin direktno putem platforme": "选择您的时间并直接通过平台预约",
    "Spoji se online ili uživo i savladaj gradivo uz pomoć stručnjaka": "在线或线下与专家一起学习并掌握知识",
    "Učitavam preporuke": "加载推荐",
    "IP": "IP",
    "Ivan P": "Ivan P",
    "MK": "MK",
    "Maja K": "Maja K",
    "Tomislav R": "Tomislav R",
    "Učitavanje profila": "加载个人资料",
    "Opišite svoje iskustvo, pristup podučavanju i zašto ste dobar izbor za studente": "描述您的经验、教学方式和为什么您是学生的最佳选择",
    "Navedite svoje kvalifikacije, certifikate, uspjehe učenika": "列出您的资格、证书、学生的成功",
    "Učitavanje recenzija": "加载评论",
    "Kad studenti ocijene vaše usluge, recenzije će se prikazati ovdje": "当学生评价您的服务时，评论将显示在这里",
    "Pretraži kvizove": "搜索测验",
    "Nema dostupnih kvizova": "没有可用的测验",
    "Nemate kreiranih kvizova": "您没有创建的测验",
    "Još niste riješili nijedan kviz": "您尚未解决任何测验",
    "Prihvaćam uvjete korištenja": "接受使用条款",
    "Učitavanje kviza": "加载测验",
    "Objavi recenziju": "发布评论",
    "Odustani": "取消",
    "Dobro došli na FerTutor": "欢迎来到 FerTutor",
    "Jednostavan put do boljih ocjena uz provjerene instruktore – online ili uživo": "通过经过验证的导师——在线或线下——轻松获得更好成绩。",
    "Jednostavan put do boljih ocjena u samo tri koraka": "只需三步即可轻松获得更好成绩。",
    "Pronađi stručnjaka koji odgovara tvom stilu učenja.": "找到适合你学习风格的专家。",
    "Strpljiv pristup i jasna objašnjenja. Rezerviraj termin i kreni učiti": "耐心的讲解和清晰的解释。预约时间，开始学习。",
    "Zahvaljujući FerTutoru našao sam instruktora iz matematike u jednom danu i napokon pohvatao gradivo za maturu. Sve je jasno, brzo i bez stresa.": "感谢 FerTutor，我在一天之内就找到了一位数学导师，终于掌握了高考的课程内容。一切都很清晰、快速且没有压力。",
    "Platforma je stvarno jednostavna za korištenje. Rezervirala sam online termin i riješila probleme iz programiranja koje sam vukla tjednima.": "这个平台真的很容易使用。我预约了一个在线课程，解决了我拖了好几周的程序设计问题。",
    "Platforma": "平台",
    "Odličan izbor instruktora i sve je transparentno. Djeca su napokon dobila rutinu, a ja imam mir jer znam da rade s provjerenim ljudima.": "导师选择很棒，一切都很透明。孩子们终于有了规律，而我也安心了，因为我知道他们和经过验证的人一起学习。",
    "Odaberi vrijeme koje ti odgovara i rezerviraj termin direktno putem platforme.":"选择适合你的时间，直接通过平台预约。",
    "Greška pri registraciji.":"注册错误。",
    "Prijava i otključajte sljedeći korak u svom učenju personalizirano, fleksibilno i vođeno vašim tempom.":"登录并解锁你学习中的下一步——个性化、灵活且由你的节奏主导。",
    "ne postoji token":"token不存在",  
    "Filteri":"筛选",
};